--[[ SPOOKY HARVEST stall: setup after importing SpookyHarvestStall.fbx
     Generated by blender/export_spooky_stall.py.

     1. Import SpookyHarvestStall.fbx (Avatar or Home tab > Import 3D) with Scale Unit = Stud,
        Merge Meshes = OFF and Insert Using Scene Position = ON.
     2. Rename the imported model to SpookyHarvestStall (or select it), paste this whole file into the
        Command Bar and press Enter.

     Every MeshPart name is <Section>__<Material>__<RRGGBB>[__T<transparency %>][__NC][__L<n>]. This script
     turns that back into Material, Color, Transparency and CanCollide, anchors everything, sorts the parts
     into folders per section, adds the "SPOOKY HARVEST" sign text, the soft PointLights and an invisible
     ShopInteractZone in front of the counter. It is safe to run again. ]]

local SIGN_TEXT = "SPOOKY HARVEST"
local LIGHTS = { -- n = { r, g, b, brightness, range }
	[1] = { 255, 166, 64, 0.7, 10 },
	[2] = { 255, 166, 64, 0.7, 10 },
	[3] = { 255, 166, 64, 0.6, 5.76 },
	[4] = { 255, 166, 64, 0.6, 5.76 },
	[5] = { 255, 166, 64, 0.55, 8.32 },
}

local model = workspace:FindFirstChild("SpookyHarvestStall")
if not model then
	local sel = game:GetService("Selection"):Get()
	model = sel[1]
end
assert(model, "Select the imported stall model (or name it SpookyHarvestStall) and run again")
model.Name = "SpookyHarvestStall"

local function folder(name)
	local f = model:FindFirstChild(name)
	if not f then
		f = Instance.new("Folder")
		f.Name = name
		f.Parent = model
	end
	return f
end

local function addSign(part)
	local old = part:FindFirstChild("SignGui")
	if old then old:Destroy() end
	local gui = Instance.new("SurfaceGui")
	gui.Name = "SignGui"
	gui.Face = Enum.NormalId.Front
	gui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	gui.PixelsPerStud = 60
	gui.LightInfluence = 0.35
	gui.Parent = part
	local label = Instance.new("TextLabel")
	label.Name = "Title"
	label.BackgroundTransparency = 1
	label.AnchorPoint = Vector2.new(0.5, 0.5)
	label.Position = UDim2.fromScale(0.5, 0.52)
	label.Size = UDim2.fromScale(0.7, 0.78)
	label.Font = Enum.Font.LuckiestGuy
	label.Text = SIGN_TEXT
	label.TextScaled = true
	label.TextColor3 = Color3.fromRGB(255, 196, 70)
	label.Parent = gui
	local stroke = Instance.new("UIStroke")
	stroke.Color = Color3.fromRGB(58, 30, 12)
	stroke.Thickness = 4
	stroke.Parent = label
	local grad = Instance.new("UIGradient")
	grad.Color = ColorSequence.new(Color3.fromRGB(255, 214, 96), Color3.fromRGB(240, 150, 40))
	grad.Rotation = 90
	grad.Parent = label
end

local count, base = 0, nil
for _, p in ipairs(model:GetDescendants()) do
	if p:IsA("MeshPart") or p:IsA("Part") then
		local bits = string.split(p.Name, "__")
		local section, matName, hex = bits[1], bits[2], bits[3]
		local isSign = section == "Sign" and bits[2] == "SignBoard"
		if isSign then matName, hex = bits[3], bits[4] end
		if matName and Enum.Material[matName] and hex then
			p.Material = Enum.Material[matName]
			p.Color = Color3.fromHex(hex)
			p.Transparency = 0
			p.CanCollide = true
			for i = 4, #bits do
				local flag = bits[i]
				if string.sub(flag, 1, 1) == "T" and tonumber(string.sub(flag, 2)) then
					p.Transparency = tonumber(string.sub(flag, 2)) / 100
				elseif flag == "NC" then
					p.CanCollide = false
				elseif string.sub(flag, 1, 1) == "L" and tonumber(string.sub(flag, 2)) then
					local l = LIGHTS[tonumber(string.sub(flag, 2))]
					local old = p:FindFirstChild("Glow")
					if old then old:Destroy() end
					local light = Instance.new("PointLight")
					light.Name = "Glow"
					light.Color = Color3.fromRGB(l[1], l[2], l[3])
					light.Brightness = l[4]
					light.Range = l[5]
					light.Shadows = false
					light.Parent = p
				end
			end
			p.CanTouch = p.CanCollide
			p.CastShadow = p.Transparency < 0.2
			p.Anchored = true
			if p:IsA("MeshPart") and not p.CanCollide then
				p.CollisionFidelity = Enum.CollisionFidelity.Box
			end
			if isSign then addSign(p) end
			p.Parent = folder(section)
			if section == "Structure" and (not base or p.Size.X * p.Size.Z > base.Size.X * base.Size.Z) then base = p end
			count = count + 1
		end
	end
end

local zone = model:FindFirstChild("ShopInteractZone") or Instance.new("Part")
zone.Name = "ShopInteractZone"
zone.Size = Vector3.new(5, 4, 3)
zone.Transparency = 1
zone.CanCollide = false
zone.CanTouch = true
zone.CastShadow = false
zone.Anchored = true
-- 0.6 studs to the player's right of the stall centre, in front of the free counter space
local cf, size = model:GetBoundingBox()
zone.CFrame = cf * CFrame.new(-0.6, 2 - size.Y / 2, -size.Z / 2 - 1.2)
zone.Parent = model
if base then model.PrimaryPart = base end
print(("SpookyHarvestStall set up: %d parts styled"):format(count))
