-- Tower of Pets: lamps from the Blender lobby as PointLight specs (generated by export_fbx.py).
-- Positions are world studs, valid when the FBX files were imported with "Insert Using Scene Position".
local M = {}

M.Lights = {
}

-- creates an invisible anchored holder part per light inside `parent` (e.g. a "Lights" Folder)
function M.build(parent)
	for _, d in ipairs(M.Lights) do
		local p = Instance.new("Part")
		p.Name = d.Name
		p.Size = Vector3.new(0.5, 0.5, 0.5)
		p.Anchored, p.CanCollide, p.CanQuery, p.CanTouch = true, false, false, false
		p.Transparency = 1
		p.Position = d.Position
		local l = Instance.new("PointLight")
		l.Color, l.Brightness, l.Range, l.Shadows = d.Color, d.Brightness, d.Range, false
		l.Parent = p
		p.Parent = parent
	end
end

return M
