-- Tower of Pets: Blender material name -> Roblox appearance (generated by export_fbx.py).
-- Every imported MeshPart is named "<Object>__<Material>"; apply(model) colours them all.
local M = {}

M.Materials = {
	["Avatar_Blue"] = {Color = Color3.fromRGB(63, 160, 231), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["Avatar_Face"] = {Color = Color3.fromRGB(63, 63, 63), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["Avatar_Green"] = {Color = Color3.fromRGB(160, 225, 137), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["Avatar_Yellow"] = {Color = Color3.fromRGB(250, 231, 137), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Cave"] = {Color = Color3.fromRGB(48, 48, 63), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Cloud"] = {Color = Color3.fromRGB(252, 253, 255), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Grass_Jungle"] = {Color = Color3.fromRGB(80, 188, 97), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Grass_Mystic"] = {Color = Color3.fromRGB(89, 175, 129), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Grass_Ruins"] = {Color = Color3.fromRGB(197, 219, 137), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Grass_Valley"] = {Color = Color3.fromRGB(126, 218, 153), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Grass_Verdant"] = {Color = Color3.fromRGB(155, 226, 118), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Label"] = {Color = Color3.fromRGB(255, 255, 255), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Label_Gold"] = {Color = Color3.fromRGB(255, 231, 137), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Lakebed"] = {Color = Color3.fromRGB(149, 173, 170), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Marker_Boss"] = {Color = Color3.fromRGB(255, 196, 63), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Marker_Checkpoint"] = {Color = Color3.fromRGB(108, 196, 255), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Marker_Egg"] = {Color = Color3.fromRGB(255, 234, 149), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Marker_MiniBoss"] = {Color = Color3.fromRGB(255, 108, 108), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Marker_Secret"] = {Color = Color3.fromRGB(218, 137, 255), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Marker_Spawn"] = {Color = Color3.fromRGB(137, 255, 196), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Path"] = {Color = Color3.fromRGB(229, 203, 162), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Reserved"] = {Color = Color3.fromRGB(255, 255, 255), Material = Enum.Material.Neon, Transparency = 0.0},
	["F1_Rock"] = {Color = Color3.fromRGB(202, 192, 183), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Rock_Dark"] = {Color = Color3.fromRGB(132, 125, 136), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Rock_Under"] = {Color = Color3.fromRGB(179, 165, 158), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Rock_Under_Dark"] = {Color = Color3.fromRGB(122, 115, 124), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Sand"] = {Color = Color3.fromRGB(246, 234, 196), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Snow"] = {Color = Color3.fromRGB(247, 249, 255), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Swamp"] = {Color = Color3.fromRGB(151, 179, 118), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Water"] = {Color = Color3.fromRGB(89, 191, 249), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Water_Swamp"] = {Color = Color3.fromRGB(111, 184, 162), Material = Enum.Material.SmoothPlastic, Transparency = 0.0},
	["F1_Waterfall"] = {Color = Color3.fromRGB(221, 243, 255), Material = Enum.Material.Neon, Transparency = 0.0},
}

-- decorative / effect pieces players should walk through
M.NoCollide = {"Particles", "Energy", "EnergyRing", "Sparkle", "Cloud", "Leaf", "Leaves", "Vine", "Banner",
	"Waterfall", "Mist", "Glow", "Grass_Tuft", "Ground_Plant", "Flower", "Rivers", "Lakes"}

-- walkable terrain: exact collision (needs Studio / command bar permission, ignored in game scripts)
M.PreciseCollision = {"_Top__", "_Cliffs__", "Natural_Bridges"}

function M.apply(root)
	for _, part in ipairs(root:GetDescendants()) do
		if part:IsA("MeshPart") then
			local key = part.Name:match("__(.+)$")
			key = key and key:gsub("%.%d+$", "")
			local spec = key and M.Materials[key]
			if key and not spec then  -- chunked parts end in _1, _2 ...
				spec = M.Materials[key:match("^(.-)_%d+$") or ""]
			end
			if spec then
				part.Color = spec.Color
				part.Material = spec.Material
				part.Transparency = spec.Transparency
				part.TextureID = ""
			end
			part.Anchored = true
			for _, pat in ipairs(M.PreciseCollision) do
				if part.Name:find(pat) then
					pcall(function() part.CollisionFidelity = Enum.CollisionFidelity.PreciseConvexDecomposition end)
					break
				end
			end
			if part.Name:find("TeleportTrigger") then  -- invisible touch volumes
				part.Transparency, part.CanCollide, part.CastShadow = 1, false, false
			else
				for _, pat in ipairs(M.NoCollide) do
					if part.Name:find(pat) then part.CanCollide = false; part.CanQuery = false; break end
				end
			end
		end
	end
end

return M
