-- Tower of Pets Floor 1: places the environment detail (trees, foliage, rocks, props, ruins, water and
-- cliff dressing, landmark pieces, background) from the Floor1_Scatter_* data modules.
-- Generated by blender/tower_of_pets/build_floor1_pack.py. See exports/TowerOfPets/Floor1/IMPORT.md.
--
-- Setup: import Floor1_Assets.fbx and put the imported model in ServerStorage named "Floor1_Assets";
-- put every Floor1_Scatter_* ModuleScript in a Folder ServerStorage.Floor1_ScatterData; then run in the
-- command bar:  require(game.ServerStorage.Floor1_Scatter).place()
-- Options: place({texture = "rbxassetid://<palette id>", lights = true, categories = {"Trees", ...}})
-- Categories: Trees, Foliage, Rocks, Props, Ruins, Water, Cliffs, Landmarks, Background
local M = {}

-- collision / shadows / streaming per category
M.Rules = {
	Trees = {collide = false, trunk = true, shadow = true},
	Foliage = {collide = false, shadow = false},
	Rocks = {collide = true, fidelity = "Hull", shadow = true, smallNoCollide = 4},
	Props = {collide = true, fidelity = "Box", shadow = true},
	Ruins = {collide = true, fidelity = "Hull", shadow = true},
	Water = {collide = false, shadow = false},
	Cliffs = {collide = false, shadow = false},
	Landmarks = {collide = false, shadow = true, persistent = true},
	Background = {collide = false, shadow = false, persistent = true},
}

-- asset -> offset (studs, Roblox axes) from the asset's ground origin to its mesh centre, at scale 1
M.Offsets = {
	Barrel = Vector3.new(0.000, 1.200, -0.000),
	Bench = Vector3.new(0.000, 1.175, -0.050),
	Broken_Column_A = Vector3.new(1.055, 4.082, -0.228),
	Broken_Column_B = Vector3.new(1.055, 6.649, -0.228),
	Broken_Wall = Vector3.new(0.558, 2.862, -1.360),
	Bush_01 = Vector3.new(-0.111, 1.127, -0.038),
	Bush_01_Mystic = Vector3.new(-0.111, 1.127, -0.038),
	Bush_02 = Vector3.new(-0.008, 1.342, -0.127),
	Bush_03 = Vector3.new(0.254, 1.711, -0.009),
	Bush_03_Mystic = Vector3.new(0.254, 1.711, -0.009),
	Cloud_A = Vector3.new(0.052, 0.316, 0.091),
	Cloud_B = Vector3.new(0.375, 0.307, -0.027),
	Cloud_C = Vector3.new(0.006, 0.322, 0.141),
	Cloud_D = Vector3.new(-0.041, 0.299, -0.017),
	Crate = Vector3.new(0.000, 1.000, -0.000),
	Crystal_Island = Vector3.new(1.141, -29.295, -0.721),
	Fern = Vector3.new(0.011, 0.953, 0.015),
	Flower_Cluster_Pink = Vector3.new(0.006, 0.758, 0.011),
	Flower_Cluster_Purple = Vector3.new(0.002, 0.756, 0.001),
	Flower_Cluster_White = Vector3.new(-0.011, 0.812, 0.006),
	Flower_Cluster_Yellow = Vector3.new(0.002, 0.756, 0.001),
	Foam_Ring = Vector3.new(0.152, 0.150, -0.000),
	Grass_Patch = Vector3.new(-0.128, 0.884, -0.174),
	Grass_Tuft = Vector3.new(0.322, 0.778, -0.255),
	Ground_Plant_01 = Vector3.new(-0.051, 0.988, 0.026),
	Ground_Plant_02 = Vector3.new(0.028, 0.512, 0.036),
	Lantern_Wood = Vector3.new(0.000, 4.800, -0.000),
	Large_Island = Vector3.new(-0.518, -55.170, 0.174),
	Leaf_Cluster_A = Vector3.new(0.089, -0.162, -0.005),
	Leaf_Cluster_B = Vector3.new(-0.010, 0.005, 0.062),
	Leaf_Cluster_C = Vector3.new(0.123, -0.132, -0.099),
	Leaf_Cluster_Low = Vector3.new(-0.971, -0.294, 0.141),
	Lily_Pads = Vector3.new(-0.332, 0.050, 0.041),
	Lily_Pads_Flower = Vector3.new(0.355, 0.265, -0.873),
	Log = Vector3.new(0.000, 1.543, -0.509),
	Medium_Island = Vector3.new(0.844, -36.195, -0.631),
	Mist_Puff = Vector3.new(-0.243, 0.802, -1.712),
	Moss_Drape_A = Vector3.new(0.000, -1.775, -0.250),
	Moss_Drape_B = Vector3.new(0.000, -3.204, -0.250),
	Mushrooms = Vector3.new(-0.148, 0.853, -0.125),
	Mushrooms_Glow = Vector3.new(-0.059, 0.892, 0.107),
	Reeds = Vector3.new(0.104, 2.652, 0.541),
	Rock_A = Vector3.new(-0.018, -0.117, -0.103),
	Rock_B = Vector3.new(-0.058, 0.043, -0.002),
	Rock_C = Vector3.new(0.060, 0.155, -0.035),
	Rock_Formation = Vector3.new(-0.167, -8.938, -1.197),
	Rock_Large = Vector3.new(0.043, -3.600, -0.626),
	Rock_Medium = Vector3.new(-0.129, -2.000, 0.168),
	Rock_Small = Vector3.new(0.195, -0.960, -0.085),
	Root_Single = Vector3.new(1.697, 0.785, 0.062),
	Rope_Barrier = Vector3.new(0.000, 1.600, -0.000),
	Ruin_Arch = Vector3.new(0.000, 7.350, -0.000),
	Signpost = Vector3.new(1.321, 3.200, -0.683),
	Small_Island = Vector3.new(0.249, -19.635, 0.177),
	Stone_Fragments = Vector3.new(1.252, 0.400, -0.167),
	Stump = Vector3.new(-0.012, 0.566, 0.029),
	Tall_Island = Vector3.new(-0.043, -31.650, 0.523),
	Temple_Platform = Vector3.new(0.000, -0.655, -0.000),
	Tree_Large_Low = Vector3.new(1.853, 11.198, 1.823),
	Tree_Large_Mystic = Vector3.new(1.853, 11.198, 1.823),
	Tree_Medium_Low = Vector3.new(-0.092, 9.398, -1.203),
	Tree_Medium_Mystic = Vector3.new(-0.092, 9.398, -1.203),
	Tree_Small_Low = Vector3.new(-0.033, 6.211, 0.582),
	Tree_Tall_Thin_Low = Vector3.new(-0.519, 10.788, -0.848),
	Tree_Tall_Thin_Mystic = Vector3.new(-0.519, 10.788, -0.848),
	Vine_Long = Vector3.new(-0.088, -3.674, 0.036),
	Waterfall_Large = Vector3.new(-0.775, -61.346, 0.919),
	Waterfall_Medium = Vector3.new(-0.222, -30.627, -0.460),
	Wood_Fence = Vector3.new(0.000, 1.500, -0.000),
}

-- tree trunks get a simple invisible cylinder collider: radius, height (scale 1)
M.Trunks = {
	Tree_Large_Low = {2.3, 9},
	Tree_Medium_Low = {1.4, 8},
	Tree_Small_Low = {1.2, 6},
	Tree_Tall_Thin_Low = {1.0, 10},
	Tree_Large_Mystic = {2.3, 9},
	Tree_Medium_Mystic = {1.4, 8},
	Tree_Small_Mystic = {1.2, 6},
	Tree_Tall_Thin_Mystic = {1.0, 10},
}

M.Transparency = {Mist_Puff = 0.45}
M.Lights = {Lantern_Wood = {7.4, 22, 1.4}}

local function findAsset(assets, name)
	local a = assets:FindFirstChild(name, true)
	if a and a:IsA("Model") then a = a:FindFirstChildWhichIsA("MeshPart", true) end
	return a
end

function M.place(opts)
	opts = opts or {}
	local assets = opts.assets or game.ServerStorage:FindFirstChild("Floor1_Assets")
	local data = opts.data or game.ServerStorage:FindFirstChild("Floor1_ScatterData")
	assert(assets, "put the imported Floor1_Assets model in ServerStorage")
	assert(data, "put the Floor1_Scatter_* modules in ServerStorage.Floor1_ScatterData")
	local only = nil
	if opts.categories then only = {}; for _, c in ipairs(opts.categories) do only[c] = true end end
	-- no categories: rebuild everything; with categories: replace only those (run one category at a time
	-- if a single big call is too slow)
	local root = (opts.parent or workspace):FindFirstChild("Floor1_Environment")
	if root and not only then root:Destroy(); root = nil end
	if not root then
		root = Instance.new("Folder"); root.Name = "Floor1_Environment"; root.Parent = opts.parent or workspace
	end
	if only then for c in pairs(only) do local old = root:FindFirstChild(c); if old then old:Destroy() end end end
	local groups, count, missing = {}, 0, {}
	for _, mod in ipairs(data:GetChildren()) do
		if not mod:IsA("ModuleScript") then continue end
		local d = require(mod)
		if only and not only[d.category] then continue end
		local rule = M.Rules[d.category] or {}
		local g = groups[d.category]
		if not g then
			g = Instance.new("Model"); g.Name = d.category
			if rule.persistent then g.ModelStreamingMode = Enum.ModelStreamingMode.Persistent end
			g.Parent = root; groups[d.category] = g
		end
		for name, arr in pairs(d.items) do
			local src = findAsset(assets, name)
			if not src then missing[name] = true; continue end
			local off = M.Offsets[name] or Vector3.zero
			local trunk, light = M.Trunks[name], M.Lights[name]
			for i = 1, #arr, 5 do
				local s = arr[i + 4]
				local base = CFrame.new(arr[i], arr[i + 1], arr[i + 2]) * CFrame.Angles(0, math.rad(arr[i + 3]), 0)
				local p = src:Clone()
				p.Name = name
				p.Size = src.Size * s
				p.CFrame = base * CFrame.new(off * s)
				p.Anchored = true
				if opts.texture then p.TextureID = opts.texture end
				p.Transparency = M.Transparency[name] or 0
				local small = rule.smallNoCollide and p.Size.Magnitude < rule.smallNoCollide * 3
				p.CanCollide = rule.collide == true and not small
				p.CanQuery, p.CanTouch = p.CanCollide, false
				p.CastShadow = rule.shadow == true
				if p.CanCollide and rule.fidelity then
					pcall(function() p.CollisionFidelity = Enum.CollisionFidelity[rule.fidelity] end)
				else
					pcall(function() p.CollisionFidelity = Enum.CollisionFidelity.Box end)
				end
				p.Parent = g
				if rule.trunk and trunk then  -- riders bump into trunks, ride under canopies
					local c = Instance.new("Part")
					c.Name = name .. "_Trunk"
					c.Shape = Enum.PartType.Cylinder
					c.Size = Vector3.new(trunk[2] * s, trunk[1] * 2 * s, trunk[1] * 2 * s)
					c.CFrame = base * CFrame.new(0, trunk[2] * s / 2, 0) * CFrame.Angles(0, 0, math.rad(90))
					c.Anchored, c.Transparency, c.CastShadow, c.CanTouch = true, 1, false, false
					c.Parent = p
				end
				if opts.lights and light then
					local a = Instance.new("Attachment"); a.Position = p.CFrame:PointToObjectSpace(
						(base * CFrame.new(0, light[1] * s, 0)).Position); a.Parent = p
					local l = Instance.new("PointLight"); l.Range = light[2]; l.Brightness = light[3]
					l.Color = Color3.fromRGB(255, 196, 120); l.Shadows = false; l.Parent = a
				end
				count += 1
			end
		end
	end
	for name in pairs(missing) do warn("Floor1_Scatter: asset not found: " .. name) end
	print(("Floor1_Scatter: placed %d pieces"):format(count))
	return root
end

-- palette texture for every asset (if the importer did not bring it in): upload Floor1_Palette.png, then
-- require(game.ServerStorage.Floor1_Scatter).setTexture("rbxassetid://<id>")
function M.setTexture(id, where)
	for _, p in ipairs((where or workspace:FindFirstChild("Floor1_Environment")):GetDescendants()) do
		if p:IsA("MeshPart") then p.TextureID = id end
	end
end

return M
