-- Tower of Pets Floor 1: bright fantasy daylight (generated by build_floor1_pack.py).
-- Run once in the command bar:  require(game.ServerStorage.Floor1_Lighting).apply()
local M = {}

local function child(parent, class, name)
	local c = parent:FindFirstChild(name)
	if c and not c:IsA(class) then c:Destroy(); c = nil end
	if not c then c = Instance.new(class); c.Name = name; c.Parent = parent end
	return c
end

function M.apply()
	local L = game:GetService("Lighting")
	-- a world this size: ShadowMap keeps soft sun shadows and costs far less than Future
	L.Technology = Enum.Technology.ShadowMap
	L.ClockTime = 13.6
	L.GeographicLatitude = 35
	L.Brightness = 2.6
	L.ExposureCompensation = 0.1
	L.Ambient = Color3.fromRGB(110, 118, 138)
	L.OutdoorAmbient = Color3.fromRGB(150, 160, 178)
	L.ColorShift_Top = Color3.fromRGB(255, 236, 205)
	L.EnvironmentDiffuseScale = 0.5
	L.EnvironmentSpecularScale = 0.3
	L.ShadowSoftness = 0.3
	L.GlobalShadows = true
	local a = child(L, "Atmosphere", "Floor1_Atmosphere")       -- soft blue haze for depth
	a.Density, a.Offset, a.Glare, a.Haze = 0.28, 0.2, 0.15, 1.4
	a.Color, a.Decay = Color3.fromRGB(199, 226, 255), Color3.fromRGB(110, 156, 212)
	local b = child(L, "BloomEffect", "Floor1_Bloom")             -- subtle glow on lanterns, water, crystals
	b.Intensity, b.Size, b.Threshold = 0.45, 28, 1.4
	local c = child(L, "ColorCorrectionEffect", "Floor1_Color")  -- vibrant, readable colours
	c.Brightness, c.Contrast, c.Saturation = 0.02, 0.06, 0.15
	c.TintColor = Color3.fromRGB(255, 250, 242)
	local r = child(L, "SunRaysEffect", "Floor1_SunRays")
	r.Intensity, r.Spread = 0.05, 0.6
	local s = child(L, "Sky", "Floor1_Sky")
	s.SunAngularSize, s.MoonAngularSize, s.CelestialBodiesShown = 14, 9, true
	local cl = child(workspace.Terrain, "Clouds", "Floor1_Clouds")
	cl.Cover, cl.Density, cl.Color = 0.55, 0.65, Color3.fromRGB(255, 255, 255)
end

return M
