-- Tower of Pets Floor 1: Verdant Village placeholder houses and market stalls (generated by
-- blender/tower_of_pets/floor1_roblox.py). NpcSpot = where a quest NPC stands (feet), Facing = look direction.
local M = {}

M.Houses = {
	{Name = "House_Elder", Role = "Elder", Position = Vector3.new(-5140.1, 70.1, 4049.8), NpcSpot = Vector3.new(-5152.2, 73.2, 4036.3), Facing = Vector3.new(-0.391, 0.0, -0.92)},
	{Name = "House_Baker", Role = "Baker", Position = Vector3.new(-5026.2, 62.6, 3996.6), NpcSpot = Vector3.new(-5036.5, 65.7, 3983.2), Facing = Vector3.new(-0.295, 0.0, -0.955)},
	{Name = "House_Smith", Role = "Smith", Position = Vector3.new(-4948.0, 54.1, 3893.7), NpcSpot = Vector3.new(-4956.8, 57.2, 3879.3), Facing = Vector3.new(-0.193, 0.0, -0.981)},
	{Name = "House_Weaver", Role = "Weaver", Position = Vector3.new(-4852.8, 57.1, 3819.1), NpcSpot = Vector3.new(-4859.1, 60.2, 3804.5), Facing = Vector3.new(-0.295, 0.0, -0.955)},
	{Name = "House_Gardener", Role = "Gardener", Position = Vector3.new(-5181.3, 65.8, 3602.2), NpcSpot = Vector3.new(-5171.3, 68.9, 3615.1), Facing = Vector3.new(0.289, 0.0, 0.957)},
	{Name = "House_Scholar", Role = "Scholar", Position = Vector3.new(-5300.3, 64.6, 3617.6), NpcSpot = Vector3.new(-5289.0, 67.7, 3630.2), Facing = Vector3.new(0.371, 0.0, 0.929)},
	{Name = "House_Fisher", Role = "Fisher", Position = Vector3.new(-5392.9, 64.1, 3638.2), NpcSpot = Vector3.new(-5379.3, 67.2, 3646.0), Facing = Vector3.new(0.621, 0.0, 0.784)},
}

M.Stalls = {
	{Name = "Stall_Fruit", Position = Vector3.new(-5077.3, 61.2, 3892.0), NpcSpot = Vector3.new(-5077.1, 61.2, 3893.0), Facing = Vector3.new(-0.281, 0.0, -0.96)},
	{Name = "Stall_Flowers", Position = Vector3.new(-5054.2, 59.6, 3843.1), NpcSpot = Vector3.new(-5053.9, 59.6, 3844.1), Facing = Vector3.new(-0.332, 0.0, -0.943)},
}

-- creates an anchored, invisible, non-colliding marker Part per NPC spot inside `parent` (e.g. a Folder
-- workspace.Floor1.NPCSpots), facing the road, with Role / House attributes for your quest scripts
function M.buildSpots(parent)
	local all = {}
	for _, h in ipairs(M.Houses) do table.insert(all, {Name = h.Name, Role = h.Role, Spot = h.NpcSpot, Facing = h.Facing}) end
	for _, s in ipairs(M.Stalls) do table.insert(all, {Name = s.Name, Role = "Merchant", Spot = s.NpcSpot, Facing = s.Facing}) end
	for _, d in ipairs(all) do
		local p = Instance.new("Part")
		p.Name = "NPC_" .. d.Name
		p.Size = Vector3.new(2, 5, 2)
		local at = d.Spot + Vector3.new(0, 2.5, 0)
		p.CFrame = CFrame.lookAt(at, at + d.Facing)
		p.Anchored, p.CanCollide, p.CanQuery, p.CanTouch = true, false, false, false
		p.Transparency = 1
		p:SetAttribute("Role", d.Role)
		p:SetAttribute("House", d.Name)
		p.Parent = parent
	end
	return #all
end

return M
