-- Tower of Pets: lamps from the Blender lobby as PointLight specs (generated by export_fbx.py).
-- Positions are world studs, valid when the FBX files were imported with "Insert Using Scene Position".
local M = {}

M.Lights = {
	{Name = "Fortress_Approach_Brazier", Position = Vector3.new(6853.0, 740.525, 919.3), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Keep_Door_Glow", Position = Vector3.new(6710.0, 804.55, 45.0), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Keep_Door_Torch_0", Position = Vector3.new(6632.0, 852.0, 68.4), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Keep_Door_Torch_2", Position = Vector3.new(6788.0, 852.0, 68.4), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Stair_Brazier_0", Position = Vector3.new(6576.75, 751.575, 698.3), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Stair_Brazier_2", Position = Vector3.new(6843.25, 751.575, 698.3), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Terrace_Brazier", Position = Vector3.new(6918.0, 824.05, 129.5), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Torch_Gate_E", Position = Vector3.new(6779.225, 822.49, 601.4), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Torch_Gate_W", Position = Vector3.new(6590.725, 822.49, 601.4), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Fortress_Yard_Brazier", Position = Vector3.new(6281.0, 826.0, 370.0), Color = Color3.fromRGB(255, 196, 129), Brightness = 3.0, Range = 60},
	{Name = "Hatchery_Light_0", Position = Vector3.new(-5279.331, 74.75, 3759.449), Color = Color3.fromRGB(231, 179, 255), Brightness = 2.93, Range = 50.9},
	{Name = "Hatchery_Light_1", Position = Vector3.new(-5276.758, 65.75, 3763.736), Color = Color3.fromRGB(255, 179, 249), Brightness = 1.6, Range = 31.2},
	{Name = "Hatchery_Light_2", Position = Vector3.new(-5288.249, 69.75, 3760.135), Color = Color3.fromRGB(149, 231, 255), Brightness = 1.4, Range = 27.0},
	{Name = "Hatchery_Light_3", Position = Vector3.new(-5274.529, 69.75, 3751.903), Color = Color3.fromRGB(149, 231, 255), Brightness = 1.4, Range = 27.0},
	{Name = "Hatchery_Light_4", Position = Vector3.new(-5269.812, 74.75, 3775.312), Color = Color3.fromRGB(255, 218, 170), Brightness = 2.8, Range = 49.3},
	{Name = "Hatchery_Light_5", Position = Vector3.new(-5280.017, 86.75, 3785.517), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.8, Range = 34.9},
	{Name = "Hatchery_Light_6", Position = Vector3.new(-5256.007, 86.75, 3771.111), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.8, Range = 34.9},
	{Name = "Portal_Brazier_Light_0", Position = Vector3.new(-5277.736, 78.75, 3928.289), Color = Color3.fromRGB(255, 206, 144), Brightness = 2.53, Range = 45.9},
	{Name = "Portal_Brazier_Light_2", Position = Vector3.new(-5318.896, 78.75, 3859.69), Color = Color3.fromRGB(255, 206, 144), Brightness = 2.53, Range = 45.9},
	{Name = "Portal_Glow_Light", Position = Vector3.new(-5302.174, 88.75, 3896.305), Color = Color3.fromRGB(160, 237, 255), Brightness = 3.0, Range = 60},
	{Name = "Shop_Light_0", Position = Vector3.new(-5172.728, 73.75, 3937.121), Color = Color3.fromRGB(255, 218, 166), Brightness = 3.0, Range = 60},
	{Name = "Shop_Light_1", Position = Vector3.new(-5162.609, 68.75, 3940.38), Color = Color3.fromRGB(255, 218, 166), Brightness = 3.0, Range = 53.2},
	{Name = "Shop_Light_2", Position = Vector3.new(-5174.614, 68.75, 3947.583), Color = Color3.fromRGB(255, 218, 166), Brightness = 3.0, Range = 53.2},
	{Name = "Shop_Light_3", Position = Vector3.new(-5178.901, 69.75, 3926.831), Color = Color3.fromRGB(255, 218, 166), Brightness = 2.8, Range = 49.3},
	{Name = "Shop_Light_4", Position = Vector3.new(-5168.011, 73.75, 3913.883), Color = Color3.fromRGB(255, 218, 166), Brightness = 2.0, Range = 38.2},
	{Name = "Shop_Light_5", Position = Vector3.new(-5195.451, 73.75, 3930.347), Color = Color3.fromRGB(255, 218, 166), Brightness = 2.0, Range = 38.2},
	{Name = "Village_Light_House_Angler", Position = Vector3.new(-1984.248, 130.157, 2619.591), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Apothecary", Position = Vector3.new(-1782.68, 141.071, 2784.179), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Baker", Position = Vector3.new(-5130.688, 73.218, 3857.074), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Brewer", Position = Vector3.new(-1723.626, 153.275, 2946.652), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Carpenter", Position = Vector3.new(-1780.268, 160.435, 2922.305), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Cooper", Position = Vector3.new(-1789.883, 136.663, 2505.745), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Elder", Position = Vector3.new(-5220.015, 78.46, 3978.591), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Fisher", Position = Vector3.new(-5339.798, 71.45, 3746.243), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Florist", Position = Vector3.new(-1878.517, 139.142, 2749.36), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Gardener", Position = Vector3.new(-5183.684, 71.352, 3788.808), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Herbalist", Position = Vector3.new(-5088.598, 70.492, 3756.035), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Librarian", Position = Vector3.new(-1830.611, 145.213, 2766.956), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Mayor", Position = Vector3.new(-2050.096, 154.377, 2920.596), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Miller", Position = Vector3.new(-1878.097, 132.598, 2637.974), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Potter", Position = Vector3.new(-1751.457, 132.433, 2580.875), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Scholar", Position = Vector3.new(-5133.945, 71.722, 3772.961), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Smith", Position = Vector3.new(-5009.821, 71.478, 3821.155), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Tailor", Position = Vector3.new(-1901.613, 159.571, 2880.511), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Light_House_Weaver", Position = Vector3.new(-4951.998, 70.587, 3808.884), Color = Color3.fromRGB(255, 215, 158), Brightness = 2.27, Range = 42.2},
	{Name = "Village_Plaza_Lamp", Position = Vector3.new(-1830.593, 132.591, 2625.205), Color = Color3.fromRGB(255, 218, 166), Brightness = 1.8, Range = 34.9},
	{Name = "Village_Plaza_Lamp.001", Position = Vector3.new(-1799.165, 132.591, 2611.326), Color = Color3.fromRGB(255, 218, 166), Brightness = 1.8, Range = 34.9},
	{Name = "Village_Plaza_Lamp.002", Position = Vector3.new(-1846.57, 132.591, 2555.729), Color = Color3.fromRGB(255, 218, 166), Brightness = 1.8, Range = 34.9},
	{Name = "Village_Plaza_Lamp.003", Position = Vector3.new(-1865.242, 132.591, 2584.569), Color = Color3.fromRGB(255, 218, 166), Brightness = 1.8, Range = 34.9},
	{Name = "Village_Plaza_Lamp.004", Position = Vector3.new(-1824.134, 132.591, 2551.106), Color = Color3.fromRGB(255, 218, 166), Brightness = 1.8, Range = 34.9},
	{Name = "Village_Plaza_Lamp.005", Position = Vector3.new(-1856.162, 132.591, 2563.537), Color = Color3.fromRGB(255, 218, 166), Brightness = 1.8, Range = 34.9},
}

-- creates an invisible anchored holder part per light inside `parent` (e.g. a "Lights" Folder)
function M.build(parent)
	for _, d in ipairs(M.Lights) do
		local p = Instance.new("Part")
		p.Name = d.Name
		p.Size = Vector3.new(0.5, 0.5, 0.5)
		p.Anchored, p.CanCollide, p.CanQuery, p.CanTouch = true, false, false, false
		p.Transparency = 1
		p.Position = d.Position
		local l = Instance.new("PointLight")
		l.Color, l.Brightness, l.Range, l.Shadows = d.Color, d.Brightness, d.Range, false
		l.Parent = p
		p.Parent = parent
	end
end

return M
