-- Tower of Pets: lamps from the Blender lobby as PointLight specs (generated by export_fbx.py).
-- Positions are world studs, valid when the FBX files were imported with "Insert Using Scene Position".
local M = {}

M.Lights = {
	{Name = "Celestial_Light_0", Position = Vector3.new(-186.412, 1720.0, -208.776), Color = Color3.fromRGB(188, 160, 255), Brightness = 3.0, Range = 60},
	{Name = "Celestial_Light_1", Position = Vector3.new(186.412, 1720.0, -208.776), Color = Color3.fromRGB(188, 160, 255), Brightness = 3.0, Range = 60},
	{Name = "Celestial_Light_2", Position = Vector3.new(0.0, 1720.0, -800.0), Color = Color3.fromRGB(188, 160, 255), Brightness = 3.0, Range = 60},
	{Name = "Cloud_Light_0", Position = Vector3.new(-123.893, 1580.0, -298.063), Color = Color3.fromRGB(225, 243, 255), Brightness = 3.0, Range = 60},
	{Name = "Cloud_Light_1", Position = Vector3.new(-0.0, 1580.0, -259.0), Color = Color3.fromRGB(225, 243, 255), Brightness = 3.0, Range = 60},
	{Name = "Cloud_Light_2", Position = Vector3.new(123.893, 1580.0, -298.063), Color = Color3.fromRGB(225, 243, 255), Brightness = 3.0, Range = 60},
	{Name = "Crystal_Light_0", Position = Vector3.new(-161.749, 910.0, -243.999), Color = Color3.fromRGB(218, 160, 255), Brightness = 3.0, Range = 60},
	{Name = "Crystal_Light_1", Position = Vector3.new(-0.0, 910.0, -193.0), Color = Color3.fromRGB(218, 160, 255), Brightness = 3.0, Range = 60},
	{Name = "Crystal_Light_2", Position = Vector3.new(161.749, 910.0, -243.999), Color = Color3.fromRGB(218, 160, 255), Brightness = 3.0, Range = 60},
	{Name = "Desert_Light_0", Position = Vector3.new(-178.956, 425.0, -219.425), Color = Color3.fromRGB(255, 225, 160), Brightness = 3.0, Range = 60},
	{Name = "Desert_Light_1", Position = Vector3.new(-0.0, 425.0, -163.0), Color = Color3.fromRGB(255, 225, 160), Brightness = 3.0, Range = 60},
	{Name = "Desert_Light_2", Position = Vector3.new(178.956, 425.0, -219.425), Color = Color3.fromRGB(255, 225, 160), Brightness = 3.0, Range = 60},
	{Name = "Divine_Light_0", Position = Vector3.new(-154.0, 1920.0, -208.264), Color = Color3.fromRGB(255, 237, 196), Brightness = 3.0, Range = 60},
	{Name = "Divine_Light_1", Position = Vector3.new(154.0, 1920.0, -208.264), Color = Color3.fromRGB(255, 237, 196), Brightness = 3.0, Range = 60},
	{Name = "Forest_Light_0", Position = Vector3.new(-150.277, 1235.0, -260.382), Color = Color3.fromRGB(179, 255, 170), Brightness = 3.0, Range = 60},
	{Name = "Forest_Light_1", Position = Vector3.new(-0.0, 1235.0, -213.0), Color = Color3.fromRGB(179, 255, 170), Brightness = 3.0, Range = 60},
	{Name = "Forest_Light_2", Position = Vector3.new(150.277, 1235.0, -260.382), Color = Color3.fromRGB(179, 255, 170), Brightness = 3.0, Range = 60},
	{Name = "Hatchery_Light_0", Position = Vector3.new(107.0, 15.0, 0.0), Color = Color3.fromRGB(231, 179, 255), Brightness = 2.93, Range = 50.9},
	{Name = "Hatchery_Light_1", Position = Vector3.new(102.0, 6.0, 0.0), Color = Color3.fromRGB(255, 179, 249), Brightness = 1.6, Range = 31.2},
	{Name = "Hatchery_Light_2", Position = Vector3.new(111.0, 10.0, -8.0), Color = Color3.fromRGB(149, 231, 255), Brightness = 1.4, Range = 27.0},
	{Name = "Hatchery_Light_3", Position = Vector3.new(111.0, 10.0, 8.0), Color = Color3.fromRGB(149, 231, 255), Brightness = 1.4, Range = 27.0},
	{Name = "Hatchery_Light_4", Position = Vector3.new(88.5, 15.0, -0.0), Color = Color3.fromRGB(255, 218, 170), Brightness = 2.8, Range = 49.3},
	{Name = "Hatchery_Light_5", Position = Vector3.new(85.0, 27.0, -14.0), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.8, Range = 34.9},
	{Name = "Hatchery_Light_6", Position = Vector3.new(85.0, 27.0, 14.0), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.8, Range = 34.9},
	{Name = "HubBase_Light_Warm", Position = Vector3.new(-0.0, 90.0, -125.0), Color = Color3.fromRGB(255, 231, 196), Brightness = 3.0, Range = 60},
	{Name = "Ice_Light_0", Position = Vector3.new(-170.926, 580.0, -230.893), Color = Color3.fromRGB(179, 225, 255), Brightness = 3.0, Range = 60},
	{Name = "Ice_Light_1", Position = Vector3.new(-0.0, 580.0, -177.0), Color = Color3.fromRGB(179, 225, 255), Brightness = 3.0, Range = 60},
	{Name = "Ice_Light_2", Position = Vector3.new(170.926, 580.0, -230.893), Color = Color3.fromRGB(179, 225, 255), Brightness = 3.0, Range = 60},
	{Name = "Jungle_Light_0", Position = Vector3.new(-186.412, 275.0, -208.776), Color = Color3.fromRGB(170, 255, 160), Brightness = 3.0, Range = 60},
	{Name = "Jungle_Light_1", Position = Vector3.new(-0.0, 275.0, -150.0), Color = Color3.fromRGB(170, 255, 160), Brightness = 3.0, Range = 60},
	{Name = "Jungle_Light_2", Position = Vector3.new(186.412, 275.0, -208.776), Color = Color3.fromRGB(170, 255, 160), Brightness = 3.0, Range = 60},
	{Name = "Kingdom_Light_0", Position = Vector3.new(-137.658, 1410.0, -278.404), Color = Color3.fromRGB(255, 237, 203), Brightness = 3.0, Range = 60},
	{Name = "Kingdom_Light_1", Position = Vector3.new(-0.0, 1410.0, -235.0), Color = Color3.fromRGB(255, 237, 203), Brightness = 3.0, Range = 60},
	{Name = "Kingdom_Light_2", Position = Vector3.new(137.658, 1410.0, -278.404), Color = Color3.fromRGB(255, 237, 203), Brightness = 3.0, Range = 60},
	{Name = "Lantern_Warm_-1_0", Position = Vector3.new(-27.0, 32.0, -136.0), Color = Color3.fromRGB(255, 211, 149), Brightness = 2.8, Range = 49.3},
	{Name = "Lantern_Warm_-1_1", Position = Vector3.new(-24.6, 14.0, -97.0), Color = Color3.fromRGB(255, 211, 149), Brightness = 2.8, Range = 49.3},
	{Name = "Lantern_Warm_1_0", Position = Vector3.new(27.0, 32.0, -136.0), Color = Color3.fromRGB(255, 211, 149), Brightness = 2.8, Range = 49.3},
	{Name = "Lantern_Warm_1_1", Position = Vector3.new(24.6, 14.0, -97.0), Color = Color3.fromRGB(255, 211, 149), Brightness = 2.8, Range = 49.3},
	{Name = "Lava_Light_0", Position = Vector3.new(-173.22, 745.0, -227.616), Color = Color3.fromRGB(255, 160, 80), Brightness = 3.0, Range = 60},
	{Name = "Lava_Light_1", Position = Vector3.new(-0.0, 745.0, -173.0), Color = Color3.fromRGB(255, 160, 80), Brightness = 3.0, Range = 60},
	{Name = "Lava_Light_2", Position = Vector3.new(173.22, 745.0, -227.616), Color = Color3.fromRGB(255, 160, 80), Brightness = 3.0, Range = 60},
	{Name = "Leaderboards_Light_Board_L", Position = Vector3.new(-64.276, 25.0, 75.731), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.1, Range = 19.1},
	{Name = "Leaderboards_Light_Board_R", Position = Vector3.new(-75.731, 25.0, 64.276), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.1, Range = 19.1},
	{Name = "Leaderboards_Light_Front_0", Position = Vector3.new(-62.225, 18.0, 62.225), Color = Color3.fromRGB(255, 239, 212), Brightness = 2.53, Range = 45.9},
	{Name = "Leaderboards_Light_Front_1", Position = Vector3.new(-53.033, 18.0, 77.075), Color = Color3.fromRGB(255, 239, 212), Brightness = 1.4, Range = 27.0},
	{Name = "Leaderboards_Light_Front_2", Position = Vector3.new(-77.075, 18.0, 53.033), Color = Color3.fromRGB(255, 239, 212), Brightness = 1.4, Range = 27.0},
	{Name = "Leaderboards_Light_Path_0", Position = Vector3.new(-41.719, 9.0, 74.246), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.13, Range = 20.1},
	{Name = "Leaderboards_Light_Path_1", Position = Vector3.new(-74.246, 9.0, 41.719), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.13, Range = 20.1},
	{Name = "Leaderboards_Light_Path_2", Position = Vector3.new(-41.366, 9.0, 86.621), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.13, Range = 20.1},
	{Name = "Leaderboards_Light_Path_3", Position = Vector3.new(-86.621, 9.0, 41.366), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.13, Range = 20.1},
	{Name = "Leaderboards_Light_Pedestal_L", Position = Vector3.new(-41.012, 4.0, 93.338), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.03, Range = 16.8},
	{Name = "Leaderboards_Light_Pedestal_R", Position = Vector3.new(-93.338, 4.0, 41.012), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.03, Range = 16.8},
	{Name = "Leaderboards_Light_Pillar_L", Position = Vector3.new(-50.487, 46.0, 92.348), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.4, Range = 27.0},
	{Name = "Leaderboards_Light_Pillar_R", Position = Vector3.new(-92.348, 46.0, 50.487), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.4, Range = 27.0},
	{Name = "PetClinic_Light_0", Position = Vector3.new(-69.296, 16.0, -69.296), Color = Color3.fromRGB(237, 246, 255), Brightness = 3.0, Range = 53.2},
	{Name = "PetClinic_Light_1", Position = Vector3.new(-74.953, 10.0, -74.953), Color = Color3.fromRGB(170, 225, 255), Brightness = 1.6, Range = 31.2},
	{Name = "PetClinic_Light_2", Position = Vector3.new(-70.711, 10.0, -59.397), Color = Color3.fromRGB(255, 221, 173), Brightness = 1.53, Range = 29.8},
	{Name = "PetClinic_Light_3", Position = Vector3.new(-59.397, 10.0, -70.711), Color = Color3.fromRGB(255, 221, 173), Brightness = 1.53, Range = 29.8},
	{Name = "PetClinic_Light_4", Position = Vector3.new(-58.69, 12.0, -58.69), Color = Color3.fromRGB(255, 221, 173), Brightness = 1.8, Range = 34.9},
	{Name = "PetClinic_Light_5", Position = Vector3.new(-65.832, 27.0, -45.184), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.6, Range = 31.2},
	{Name = "PetClinic_Light_6", Position = Vector3.new(-45.184, 27.0, -65.832), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.6, Range = 31.2},
	{Name = "PetGym_Light_0", Position = Vector3.new(70.711, 17.0, 70.711), Color = Color3.fromRGB(237, 246, 255), Brightness = 3.0, Range = 53.2},
	{Name = "PetGym_Light_1", Position = Vector3.new(70.711, 6.0, 70.711), Color = Color3.fromRGB(149, 203, 255), Brightness = 1.6, Range = 31.2},
	{Name = "PetGym_Light_2", Position = Vector3.new(81.317, 11.0, 68.589), Color = Color3.fromRGB(255, 221, 173), Brightness = 1.53, Range = 29.8},
	{Name = "PetGym_Light_3", Position = Vector3.new(68.589, 11.0, 81.317), Color = Color3.fromRGB(255, 221, 173), Brightness = 1.53, Range = 29.8},
	{Name = "PetGym_Light_4", Position = Vector3.new(58.69, 12.0, 58.69), Color = Color3.fromRGB(255, 221, 173), Brightness = 1.8, Range = 34.9},
	{Name = "PetGym_Light_5", Position = Vector3.new(66.539, 28.0, 44.477), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.6, Range = 31.2},
	{Name = "PetGym_Light_6", Position = Vector3.new(44.477, 28.0, 66.539), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.6, Range = 31.2},
	{Name = "Portal_Glow_Purple", Position = Vector3.new(0.0, 30.0, -138.0), Color = Color3.fromRGB(211, 149, 255), Brightness = 3.0, Range = 60},
	{Name = "Shadow_Light_0", Position = Vector3.new(-154.866, 1070.0, -253.829), Color = Color3.fromRGB(196, 124, 255), Brightness = 3.0, Range = 60},
	{Name = "Shadow_Light_1", Position = Vector3.new(-0.0, 1070.0, -205.0), Color = Color3.fromRGB(196, 124, 255), Brightness = 3.0, Range = 60},
	{Name = "Shadow_Light_2", Position = Vector3.new(154.866, 1070.0, -253.829), Color = Color3.fromRGB(196, 124, 255), Brightness = 3.0, Range = 60},
	{Name = "Shop_Light_0", Position = Vector3.new(67.882, 14.0, -67.882), Color = Color3.fromRGB(255, 218, 166), Brightness = 3.0, Range = 60},
	{Name = "Shop_Light_1", Position = Vector3.new(68.589, 9.0, -78.489), Color = Color3.fromRGB(255, 218, 166), Brightness = 3.0, Range = 53.2},
	{Name = "Shop_Light_2", Position = Vector3.new(78.489, 9.0, -68.589), Color = Color3.fromRGB(255, 218, 166), Brightness = 3.0, Range = 53.2},
	{Name = "Shop_Light_3", Position = Vector3.new(59.397, 10.0, -59.397), Color = Color3.fromRGB(255, 218, 166), Brightness = 2.8, Range = 49.3},
	{Name = "Shop_Light_4", Position = Vector3.new(44.194, 14.0, -66.822), Color = Color3.fromRGB(255, 218, 166), Brightness = 2.0, Range = 38.2},
	{Name = "Shop_Light_5", Position = Vector3.new(66.822, 14.0, -44.194), Color = Color3.fromRGB(255, 218, 166), Brightness = 2.0, Range = 38.2},
	{Name = "TradingPortal_Light_Outer_L", Position = Vector3.new(-98.5, 29.0, 33.0), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.2, Range = 22.0},
	{Name = "TradingPortal_Light_Outer_R", Position = Vector3.new(-98.5, 29.0, -33.0), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.2, Range = 22.0},
	{Name = "TradingPortal_Light_Path_0", Position = Vector3.new(-74.5, 9.0, 21.5), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.13, Range = 20.1},
	{Name = "TradingPortal_Light_Path_1", Position = Vector3.new(-74.5, 9.0, -21.5), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.13, Range = 20.1},
	{Name = "TradingPortal_Light_Path_2", Position = Vector3.new(-86.0, 9.0, 28.5), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.13, Range = 20.1},
	{Name = "TradingPortal_Light_Path_3", Position = Vector3.new(-86.0, 9.0, -28.5), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.13, Range = 20.1},
	{Name = "TradingPortal_Light_Pillar_L", Position = Vector3.new(-98.5, 38.5, 16.8), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.4, Range = 27.0},
	{Name = "TradingPortal_Light_Pillar_R", Position = Vector3.new(-98.5, 38.5, -16.8), Color = Color3.fromRGB(255, 218, 170), Brightness = 1.4, Range = 27.0},
	{Name = "TradingPortal_Light_Portal_0", Position = Vector3.new(-97.0, 11.5, -0.0), Color = Color3.fromRGB(206, 153, 255), Brightness = 2.53, Range = 45.9},
	{Name = "TradingPortal_Light_Portal_1", Position = Vector3.new(-104.5, 11.5, 0.0), Color = Color3.fromRGB(206, 153, 255), Brightness = 2.0, Range = 38.2},
	{Name = "TradingPortal_Light_Portal_2", Position = Vector3.new(-86.0, 5.5, -0.0), Color = Color3.fromRGB(206, 153, 255), Brightness = 1.27, Range = 23.8},
}

-- creates an invisible anchored holder part per light inside `parent` (e.g. a "Lights" Folder)
function M.build(parent)
	for _, d in ipairs(M.Lights) do
		local p = Instance.new("Part")
		p.Name = d.Name
		p.Size = Vector3.new(0.5, 0.5, 0.5)
		p.Anchored, p.CanCollide, p.CanQuery, p.CanTouch = true, false, false, false
		p.Transparency = 1
		p.Position = d.Position
		local l = Instance.new("PointLight")
		l.Color, l.Brightness, l.Range, l.Shadows = d.Color, d.Brightness, d.Range, false
		l.Parent = p
		p.Parent = parent
	end
end

return M
