"""TOWER OF PETS - Floor 1 Roblox delivery for the environment detail pass.

write_scatter()  -> exports/TowerOfPets/Floor1/Scatter/Floor1_Scatter_<Category>_<n>.lua (placement data ModuleScripts)
                    + Floor1_Scatter.lua (the placer) + Floor1_Lighting.lua
export_assets()  -> exports/TowerOfPets/Floor1/Floor1_Assets.fbx + Floor1_Palette.png: every scattered asset once, as a
                    single MeshPart coloured by a small palette texture (one draw-call-friendly mesh per asset instead
                    of one MeshPart per material), all at the origin.
Placement data is in Roblox coordinates: (x, y, z) Blender -> (x, z, -y); rotation about Blender Z = about Roblox Y.
"""
import os, math, json, struct, zlib

# collision / streaming rules per category (also documented in IMPORT.md)
RULES = {
    'Trees':      'collide = false, trunk = true, shadow = true',
    'Foliage':    'collide = false, shadow = false',
    'Rocks':      'collide = true, fidelity = "Hull", shadow = true, smallNoCollide = 4',
    'Props':      'collide = true, fidelity = "Box", shadow = true',
    'Ruins':      'collide = true, fidelity = "Hull", shadow = true',
    'Water':      'collide = false, shadow = false',
    'Cliffs':     'collide = false, shadow = false',
    'Landmarks':  'collide = false, shadow = true, persistent = true',
    'Background': 'collide = false, shadow = false, persistent = true',
}
TRUNKS = {  # asset -> (trunk radius, collider height) at scale 1, studs
    'Tree_Large_Low': (2.3, 9), 'Tree_Medium_Low': (1.4, 8), 'Tree_Small_Low': (1.2, 6), 'Tree_Tall_Thin_Low': (1.0, 10),
    'Tree_Large_Mystic': (2.3, 9), 'Tree_Medium_Mystic': (1.4, 8), 'Tree_Small_Mystic': (1.2, 6),
    'Tree_Tall_Thin_Mystic': (1.0, 10),
}
TRANSPARENT = {'Mist_Puff': 0.45}
LIGHTS = {'Lantern_Wood': (7.4, 22, 1.4)}      # asset -> (light height at scale 1, range, brightness)


def to_roblox(x, y, z):
    return x, z, -y


# ---------------------------------------------------------------- scatter data + scripts
def write_scatter(placed, offsets, out_dir, max_chars=150_000):
    sdir = os.path.join(out_dir, 'Scatter')
    os.makedirs(sdir, exist_ok=True)
    for f in os.listdir(sdir):
        if f.startswith('Floor1_Scatter_') and f.endswith('.lua'):
            os.remove(os.path.join(sdir, f))
    by_cat = {}
    for cat, asset, x, y, z, rot, s in placed:
        rx, ry, rz = to_roblox(x, y, z)
        by_cat.setdefault(cat, {}).setdefault(asset, []).append(
            f'{rx:.0f},{ry:.1f},{rz:.0f},{math.degrees(rot) % 360:.0f},{s:.2f}')
    files = []
    for cat in sorted(by_cat):
        chunks, cur, size = [], {}, 0
        for asset in sorted(by_cat[cat]):
            for item in by_cat[cat][asset]:
                if size > max_chars:
                    chunks.append(cur); cur, size = {}, 0
                cur.setdefault(asset, []).append(item)
                size += len(item) + 1
        if cur:
            chunks.append(cur)
        for k, ch in enumerate(chunks):
            name = f'Floor1_Scatter_{cat}_{k + 1}'
            L = [f'-- Tower of Pets Floor 1 scatter: {cat} ({sum(len(v) for v in ch.values())} placements).',
                 '-- Generated by blender/tower_of_pets/build_floor1_pack.py - x, y, z (studs), yaw (deg), scale.',
                 'return {', f'\tcategory = "{cat}",', '\titems = {']
            for asset in sorted(ch):
                L.append(f'\t\t{asset} = {{{",".join(ch[asset])}}},')
            L += ['\t},', '}', '']
            with open(os.path.join(sdir, name + '.lua'), 'w') as f:
                f.write('\n'.join(L))
            files.append(name)
    write_placer(out_dir, offsets)
    write_lighting(out_dir)
    return files, {c: sum(len(v) for v in by_cat[c].values()) for c in by_cat}


def write_placer(out_dir, offsets):
    L = ['-- Tower of Pets Floor 1: places the environment detail (trees, foliage, rocks, props, ruins, water and',
         '-- cliff dressing, landmark pieces, background) from the Floor1_Scatter_* data modules.',
         '-- Generated by blender/tower_of_pets/build_floor1_pack.py. See exports/TowerOfPets/Floor1/IMPORT.md.',
         '--',
         '-- Setup: import Floor1_Assets.fbx and put the imported model in ServerStorage named "Floor1_Assets";',
         '-- put every Floor1_Scatter_* ModuleScript in a Folder ServerStorage.Floor1_ScatterData; then run in the',
         '-- command bar:  require(game.ServerStorage.Floor1_Scatter).place()',
         '-- Options: place({texture = "rbxassetid://<palette id>", lights = true, categories = {"Trees", ...}})',
         '-- Categories: Trees, Foliage, Rocks, Props, Ruins, Water, Cliffs, Landmarks, Background',
         'local M = {}', '',
         '-- collision / shadows / streaming per category',
         'M.Rules = {']
    for cat, r in RULES.items():
        L.append(f'\t{cat} = {{{r}}},')
    L += ['}', '',
          '-- asset -> offset (studs, Roblox axes) from the asset\'s ground origin to its mesh centre, at scale 1',
          'M.Offsets = {']
    for name in sorted(offsets):
        ox, oy, oz = offsets[name]
        L.append(f'\t{name} = Vector3.new({ox:.3f}, {oy:.3f}, {oz:.3f}),')
    L += ['}', '', '-- tree trunks get a simple invisible cylinder collider: radius, height (scale 1)', 'M.Trunks = {']
    for name, (r, h) in TRUNKS.items():
        L.append(f'\t{name} = {{{r}, {h}}},')
    L += ['}', '', 'M.Transparency = {' + ', '.join(f'{k} = {v}' for k, v in TRANSPARENT.items()) + '}',
          'M.Lights = {' + ', '.join(f'{k} = {{{h}, {r}, {b}}}' for k, (h, r, b) in LIGHTS.items()) + '}', '',
          'local function findAsset(assets, name)',
          '\tlocal a = assets:FindFirstChild(name, true)',
          '\tif a and a:IsA("Model") then a = a:FindFirstChildWhichIsA("MeshPart", true) end',
          '\treturn a',
          'end', '',
          'function M.place(opts)',
          '\topts = opts or {}',
          '\tlocal assets = opts.assets or game.ServerStorage:FindFirstChild("Floor1_Assets")',
          '\tlocal data = opts.data or game.ServerStorage:FindFirstChild("Floor1_ScatterData")',
          '\tassert(assets, "put the imported Floor1_Assets model in ServerStorage")',
          '\tassert(data, "put the Floor1_Scatter_* modules in ServerStorage.Floor1_ScatterData")',
          '\tlocal only = nil',
          '\tif opts.categories then only = {}; for _, c in ipairs(opts.categories) do only[c] = true end end',
          '\t-- no categories: rebuild everything; with categories: replace only those (run one category at a time',
          '\t-- if a single big call is too slow)',
          '\tlocal root = (opts.parent or workspace):FindFirstChild("Floor1_Environment")',
          '\tif root and not only then root:Destroy(); root = nil end',
          '\tif not root then',
          '\t\troot = Instance.new("Folder"); root.Name = "Floor1_Environment"; root.Parent = opts.parent or workspace',
          '\tend',
          '\tif only then for c in pairs(only) do local old = root:FindFirstChild(c); if old then old:Destroy() end end end',
          '\tlocal groups, count, missing = {}, 0, {}',
          '\tfor _, mod in ipairs(data:GetChildren()) do',
          '\t\tif not mod:IsA("ModuleScript") then continue end',
          '\t\tlocal d = require(mod)',
          '\t\tif only and not only[d.category] then continue end',
          '\t\tlocal rule = M.Rules[d.category] or {}',
          '\t\tlocal g = groups[d.category]',
          '\t\tif not g then',
          '\t\t\tg = Instance.new("Model"); g.Name = d.category',
          '\t\t\tif rule.persistent then g.ModelStreamingMode = Enum.ModelStreamingMode.Persistent end',
          '\t\t\tg.Parent = root; groups[d.category] = g',
          '\t\tend',
          '\t\tfor name, arr in pairs(d.items) do',
          '\t\t\tlocal src = findAsset(assets, name)',
          '\t\t\tif not src then missing[name] = true; continue end',
          '\t\t\tlocal off = M.Offsets[name] or Vector3.zero',
          '\t\t\tlocal trunk, light = M.Trunks[name], M.Lights[name]',
          '\t\t\tfor i = 1, #arr, 5 do',
          '\t\t\t\tlocal s = arr[i + 4]',
          '\t\t\t\tlocal base = CFrame.new(arr[i], arr[i + 1], arr[i + 2]) * CFrame.Angles(0, math.rad(arr[i + 3]), 0)',
          '\t\t\t\tlocal p = src:Clone()',
          '\t\t\t\tp.Name = name',
          '\t\t\t\tp.Size = src.Size * s',
          '\t\t\t\tp.CFrame = base * CFrame.new(off * s)',
          '\t\t\t\tp.Anchored = true',
          '\t\t\t\tif opts.texture then p.TextureID = opts.texture end',
          '\t\t\t\tp.Transparency = M.Transparency[name] or 0',
          '\t\t\t\tlocal small = rule.smallNoCollide and p.Size.Magnitude < rule.smallNoCollide * 3',
          '\t\t\t\tp.CanCollide = rule.collide == true and not small',
          '\t\t\t\tp.CanQuery, p.CanTouch = p.CanCollide, false',
          '\t\t\t\tp.CastShadow = rule.shadow == true',
          '\t\t\t\tif p.CanCollide and rule.fidelity then',
          '\t\t\t\t\tpcall(function() p.CollisionFidelity = Enum.CollisionFidelity[rule.fidelity] end)',
          '\t\t\t\telse',
          '\t\t\t\t\tpcall(function() p.CollisionFidelity = Enum.CollisionFidelity.Box end)',
          '\t\t\t\tend',
          '\t\t\t\tp.Parent = g',
          '\t\t\t\tif rule.trunk and trunk then  -- riders bump into trunks, ride under canopies',
          '\t\t\t\t\tlocal c = Instance.new("Part")',
          '\t\t\t\t\tc.Name = name .. "_Trunk"',
          '\t\t\t\t\tc.Shape = Enum.PartType.Cylinder',
          '\t\t\t\t\tc.Size = Vector3.new(trunk[2] * s, trunk[1] * 2 * s, trunk[1] * 2 * s)',
          '\t\t\t\t\tc.CFrame = base * CFrame.new(0, trunk[2] * s / 2, 0) * CFrame.Angles(0, 0, math.rad(90))',
          '\t\t\t\t\tc.Anchored, c.Transparency, c.CastShadow, c.CanTouch = true, 1, false, false',
          '\t\t\t\t\tc.Parent = p',
          '\t\t\t\tend',
          '\t\t\t\tif opts.lights and light then',
          '\t\t\t\t\tlocal a = Instance.new("Attachment"); a.Position = p.CFrame:PointToObjectSpace(',
          '\t\t\t\t\t\t(base * CFrame.new(0, light[1] * s, 0)).Position); a.Parent = p',
          '\t\t\t\t\tlocal l = Instance.new("PointLight"); l.Range = light[2]; l.Brightness = light[3]',
          '\t\t\t\t\tl.Color = Color3.fromRGB(255, 196, 120); l.Shadows = false; l.Parent = a',
          '\t\t\t\tend',
          '\t\t\t\tcount += 1',
          '\t\t\tend',
          '\t\tend',
          '\tend',
          '\tfor name in pairs(missing) do warn("Floor1_Scatter: asset not found: " .. name) end',
          '\tprint(("Floor1_Scatter: placed %d pieces"):format(count))',
          '\treturn root',
          'end', '',
          '-- palette texture for every asset (if the importer did not bring it in): upload Floor1_Palette.png, then',
          '-- require(game.ServerStorage.Floor1_Scatter).setTexture("rbxassetid://<id>")',
          'function M.setTexture(id, where)',
          '\tfor _, p in ipairs((where or workspace:FindFirstChild("Floor1_Environment")):GetDescendants()) do',
          '\t\tif p:IsA("MeshPart") then p.TextureID = id end',
          '\tend',
          'end', '', 'return M', '']
    with open(os.path.join(out_dir, 'Floor1_Scatter.lua'), 'w') as f:
        f.write('\n'.join(L))


def write_lighting(out_dir):
    L = ['-- Tower of Pets Floor 1: bright fantasy daylight (generated by build_floor1_pack.py).',
         '-- Run once in the command bar:  require(game.ServerStorage.Floor1_Lighting).apply()',
         'local M = {}', '',
         'local function child(parent, class, name)',
         '\tlocal c = parent:FindFirstChild(name)',
         '\tif c and not c:IsA(class) then c:Destroy(); c = nil end',
         '\tif not c then c = Instance.new(class); c.Name = name; c.Parent = parent end',
         '\treturn c',
         'end', '',
         'function M.apply()',
         '\tlocal L = game:GetService("Lighting")',
         '\t-- a world this size: ShadowMap keeps soft sun shadows and costs far less than Future',
         '\tL.Technology = Enum.Technology.ShadowMap',
         '\tL.ClockTime = 13.6',
         '\tL.GeographicLatitude = 35',
         '\tL.Brightness = 2.6',
         '\tL.ExposureCompensation = 0.1',
         '\tL.Ambient = Color3.fromRGB(110, 118, 138)',
         '\tL.OutdoorAmbient = Color3.fromRGB(150, 160, 178)',
         '\tL.ColorShift_Top = Color3.fromRGB(255, 236, 205)',
         '\tL.EnvironmentDiffuseScale = 0.5',
         '\tL.EnvironmentSpecularScale = 0.3',
         '\tL.ShadowSoftness = 0.3',
         '\tL.GlobalShadows = true',
         '\tlocal a = child(L, "Atmosphere", "Floor1_Atmosphere")       -- soft blue haze for depth',
         '\ta.Density, a.Offset, a.Glare, a.Haze = 0.28, 0.2, 0.15, 1.4',
         '\ta.Color, a.Decay = Color3.fromRGB(199, 226, 255), Color3.fromRGB(110, 156, 212)',
         '\tlocal b = child(L, "BloomEffect", "Floor1_Bloom")             -- subtle glow on lanterns, water, crystals',
         '\tb.Intensity, b.Size, b.Threshold = 0.45, 28, 1.4',
         '\tlocal c = child(L, "ColorCorrectionEffect", "Floor1_Color")  -- vibrant, readable colours',
         '\tc.Brightness, c.Contrast, c.Saturation = 0.02, 0.06, 0.15',
         '\tc.TintColor = Color3.fromRGB(255, 250, 242)',
         '\tlocal r = child(L, "SunRaysEffect", "Floor1_SunRays")',
         '\tr.Intensity, r.Spread = 0.05, 0.6',
         '\tlocal s = child(L, "Sky", "Floor1_Sky")',
         '\ts.SunAngularSize, s.MoonAngularSize, s.CelestialBodiesShown = 14, 9, true',
         '\tlocal cl = child(workspace.Terrain, "Clouds", "Floor1_Clouds")',
         '\tcl.Cover, cl.Density, cl.Color = 0.55, 0.65, Color3.fromRGB(255, 255, 255)',
         'end', '', 'return M', '']
    with open(os.path.join(out_dir, 'Floor1_Lighting.lua'), 'w') as f:
        f.write('\n'.join(L))


# ---------------------------------------------------------------- asset library export (palette textured)
def png_write(path, w, h, rgb_rows):
    raw = b''.join(b'\x00' + bytes(row) for row in rgb_rows)
    def chunk(t, d):
        return struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
    with open(path, 'wb') as f:
        f.write(b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0))
                + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def export_assets(blend, out_dir):
    """every asset used by the scatter, once, as one palette-textured MeshPart at the origin"""
    import bpy, bmesh
    import export_fbx
    bpy.ops.wm.open_mainfile(filepath=blend)
    used = sorted({o.data.name for o in bpy.data.collections['SCATTER'].all_objects if o.type == 'MESH'})
    srcs = {n[len('ASSET_'):]: bpy.data.meshes[n] for n in used if n.startswith('ASSET_')}
    mats = sorted({m.name for me in srcs.values() for m in me.materials if m})
    N = 1
    while N * N < len(mats):
        N *= 2
    cell = 8
    cols = {}
    for k, name in enumerate(mats):
        c = export_fbx.rep_color(bpy.data.materials[name])
        cols[name] = (k // N, k % N, tuple(int(round(export_fbx.lin2srgb(v) * 255)) for v in c))
    rows = []
    for r in range(N * cell):
        row = []
        for cc in range(N * cell):
            k = (r // cell) * N + cc // cell
            rgb = cols[mats[k]][2] if k < len(mats) else (255, 0, 255)
            row += list(rgb)
        rows.append(row)
    png = os.path.join(out_dir, 'Floor1_Palette.png')
    png_write(png, N * cell, N * cell, rows)
    img = bpy.data.images.load(png)
    pal = bpy.data.materials.new('F1_Palette')
    pal.use_nodes = True
    nt = pal.node_tree
    tex = nt.nodes.new('ShaderNodeTexImage'); tex.image = img; tex.interpolation = 'Closest'
    nt.links.new(tex.outputs['Color'], nt.nodes['Principled BSDF'].inputs['Base Color'])
    scene_coll = bpy.data.collections.new('_ASSET_EXPORT')
    bpy.context.scene.collection.children.link(scene_coll)
    objs, offsets, tris = [], {}, 0
    for name, src in sorted(srcs.items()):
        bm = bmesh.new(); bm.from_mesh(src)
        bmesh.ops.triangulate(bm, faces=bm.faces[:])
        uv = bm.loops.layers.uv.new('Palette')
        for f in bm.faces:
            m = src.materials[f.material_index] if f.material_index < len(src.materials) else None
            r, c, _ = cols.get(m.name if m else mats[0], cols[mats[0]])
            u, v = (c + 0.5) / N, 1 - (r + 0.5) / N
            for lp in f.loops:
                lp[uv].uv = (u, v)
            f.material_index = 0
        me = bpy.data.meshes.new(name)
        bm.to_mesh(me); bm.free()
        me.materials.append(pal)
        ob = bpy.data.objects.new(name, me)
        scene_coll.objects.link(ob)
        objs.append(ob)
        xs = [v.co for v in me.vertices]
        ctr = [(max(c[a] for c in xs) + min(c[a] for c in xs)) / 2 for a in range(3)]
        offsets[name] = to_roblox(*ctr)
        tris += len(me.polygons)
    for o in bpy.context.view_layer.objects:
        o.select_set(False)
    for o in objs:
        o.select_set(True)
    path = os.path.join(out_dir, 'Floor1_Assets.fbx')
    bpy.ops.export_scene.fbx(filepath=path, use_selection=True, object_types={'MESH'}, apply_unit_scale=True,
                             apply_scale_options='FBX_SCALE_NONE', global_scale=1.0, axis_forward='-Z', axis_up='Y',
                             mesh_smooth_type='FACE', use_mesh_modifiers=False, add_leaf_bones=False, bake_anim=False,
                             path_mode='COPY', embed_textures=True, use_custom_props=False)
    print(f'Floor1_Assets: {len(objs)} assets, {tris:,} tris, palette {N}x{N} ({len(mats)} colours), '
          f'{os.path.getsize(path) / 1e6:.2f} MB')
    return offsets, dict(assets=len(objs), triangles=tris, palette_colours=len(mats))


# ---------------------------------------------------------------- one-click script bundle for Studio
def write_rbxmx(out_dir):
    """Floor1_Scripts.rbxmx: Floor1_Materials, Floor1_Scatter, Floor1_Lighting and the Floor1_ScatterData folder as
    ModuleScripts - in Studio: right-click ServerStorage > Insert from File... > this file"""
    from xml.sax.saxutils import escape
    ref = [0]

    def item(cls, name, source=None, children=()):
        ref[0] += 1
        props = f'<string name="Name">{escape(name)}</string>'
        if source is not None:
            assert ']]>' not in source
            props += f'<ProtectedString name="Source"><![CDATA[{source}]]></ProtectedString>'
        return (f'<Item class="{cls}" referent="RBX{ref[0]}"><Properties>{props}</Properties>'
                + ''.join(children) + '</Item>')

    def read(p):
        with open(p) as f:
            return f.read()
    items = [item('ModuleScript', n, read(os.path.join(out_dir, n + '.lua')))
             for n in ('Floor1_Materials', 'Floor1_Scatter', 'Floor1_Lighting')]
    sdir = os.path.join(out_dir, 'Scatter')
    mods = [item('ModuleScript', f[:-4], read(os.path.join(sdir, f))) for f in sorted(os.listdir(sdir)) if f.endswith('.lua')]
    items.append(item('Folder', 'Floor1_ScatterData', children=mods))
    xml = ('<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" '
           'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
           'xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4">'
           + ''.join(items) + '</roblox>')
    path = os.path.join(out_dir, 'Floor1_Scripts.rbxmx')
    with open(path, 'w') as f:
        f.write(xml)
    print(f'Floor1_Scripts.rbxmx: {len(items) - 1} modules + {len(mods)} scatter data modules, '
          f'{os.path.getsize(path) / 1e6:.2f} MB')
    return path
